import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Hackathon",
  description: "Generated by hacker",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
